### ISSUE TITLE
Set Up Kanban for Reservify

### ISSUE THREAD

**Issue by Yothu** [Yothu/reservify-front-end#14]
The project for this application is separated into two repositories, the front end, and the back end:
[Back-end](https://github.com/Yothu/reservify-back-end)
[Front-end](https://github.com/Yothu/reservify-front-end)

People on the team: 5

## Overview of the kanban board
![image](https://user-images.githubusercontent.com/53308506/171664733-c6a2195b-42d1-4634-9c6e-205a4085f6af.png)
<hr>

## Front-end tasks:

![image](https://user-images.githubusercontent.com/53308506/171663501-1b92a53c-3d63-4d8d-9a68-6d3b96aa0dea.png)
![image](https://user-images.githubusercontent.com/53308506/171663762-fffdcea4-068e-4d70-870f-2adc7135b75d.png)
![image](https://user-images.githubusercontent.com/53308506/171663808-ab4b4e1a-db94-4e32-a4bb-fc2041bb4988.png)
<hr>

## Back-end tasks :

![image](https://user-images.githubusercontent.com/53308506/171664214-b8788c8c-8c3d-4cf1-8074-b08d8a76edf2.png)
![image](https://user-images.githubusercontent.com/53308506/171664269-d11995d3-bc62-4542-bfb9-32c0f554dec2.png)

<img src="https://media3.giphy.com/media/Lopx9eUi34rbq/giphy.gif"/>

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes

- [x] I'm not sure if is required to separate the project into two diffs (front and back), according to the mandatory requirements, this said: 

1. Students should have sent you a link to the GitHub issue that has a link to the GitHub project. Please, use the issue's comments to communicate with students.

It looks like everything could be on the same project in place to separate it two, what do you think?

- [x] It looks like in the back-end project, you're using an additional column after done, I consider this isn't required. May you remove it?
![image](https://user-images.githubusercontent.com/20563252/171518977-d2054d17-3857-485d-bc03-e415f7d36236.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by eduardosancho** [comment]
Hello @vichuge, thank you dearly for your review.

We moved all issues into a [single Kanban board](https://github.com/Yothu/reservify-front-end/projects/1) and removed the trailing column. 😄

**Comment by MuriloRoque** [comment]
Hi @Yothu, @Bondok6, @eduardosancho, @sj1978,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
